/*********************************************************************************
 Copyright 2010-2017 Ellucian Company L.P. and its affiliates.
 **********************************************************************************/
package net.hedtech.banner.seeddata

/**
 * Class to define table object to store crud activity that is printed at the end of the process
 */
public class APIClasses {

    /**
     * To add a new class to execute the BannerAPI,  add the entry to the API map
     * The class TableDriver will will instantiate the class
     *        Class.forName(className).newInstance(connectInfo, conn, connectCall, xmlRec)
     */


    def API = [
            'SOBTERM'               : 'net.hedtech.banner.seeddata.TermRulesDML',
            'SPRIDEN_VIEW'          : 'net.hedtech.banner.seeddata.GeneralPersonXML',
            'SPRIDEN'               : 'net.hedtech.banner.seeddata.PersonIDDML',
            'SPRTELE'               : 'net.hedtech.banner.seeddata.TelephoneDML',
            'SPBPERS'               : 'net.hedtech.banner.seeddata.PersonBioDML',
            'SPRADDR'               : 'net.hedtech.banner.seeddata.AddressDML',
            'GOREMAL'               : 'net.hedtech.banner.seeddata.EmailDML',
            'SIBINST'               : 'net.hedtech.banner.seeddata.FacultyDML',
            'SIRASGN'               : 'net.hedtech.banner.seeddata.FacultyAssignmentsDML',
            'SSBSECT'               : 'net.hedtech.banner.seeddata.ScheduleDML',
            'SSRMEET'               : 'net.hedtech.banner.seeddata.ClassTimesDML',
            'SCBCRSE'               : 'net.hedtech.banner.seeddata.CatalogDML',
            'SCRRATT'               : 'net.hedtech.banner.seeddata.CatalogRulesDML',
            'SCRRCHR'               : 'net.hedtech.banner.seeddata.CatalogRulesDML',
            'SCRRDEP'               : 'net.hedtech.banner.seeddata.CatalogRulesDML',
            'SCRINTG'               : 'net.hedtech.banner.seeddata.CatalogRulesDML',
            'SCRCLBD'               : 'net.hedtech.banner.seeddata.CatalogRulesDML',
            'SCRMEXC'               : 'net.hedtech.banner.seeddata.CatalogRulesDML',
            'SSRRATT'               : 'net.hedtech.banner.seeddata.ScheduleRulesDML',
            'SSRRCHR'               : 'net.hedtech.banner.seeddata.ScheduleRulesDML',
            'SSRRDEP'               : 'net.hedtech.banner.seeddata.ScheduleRulesDML',
            'SSRCLBD'               : 'net.hedtech.banner.seeddata.ScheduleRulesDML',
            'SSBWLSC'               : 'net.hedtech.banner.seeddata.ScheduleRulesDML',
            'SGBSTDN'               : 'net.hedtech.banner.seeddata.GeneralStudentDML',
            'SORLCUR'               : 'net.hedtech.banner.seeddata.ConcurrentCurriculumDML',
            'SORLFOS'               : 'net.hedtech.banner.seeddata.FieldOfStudyDML',
            'SHRDGMR'               : 'net.hedtech.banner.seeddata.HistoryOutcomeDML',
            'SARADAP'               : 'net.hedtech.banner.seeddata.AdmissionsApplicationDML',
            'SRBRECR'               : 'net.hedtech.banner.seeddata.RecruitDML',
            'STUDENT_SPRIDEN'       : 'net.hedtech.banner.seeddata.StudentPersonIDDML',
            'FACULTY_SPRIDEN'       : 'net.hedtech.banner.seeddata.FacultyPersonIDDML',
            'ADVISING_SPRIDEN'      : 'net.hedtech.banner.seeddata.AdvisingPersonIDDML',
            'CURRICULUMBACK'        : 'net.hedtech.banner.seeddata.CurriculumBacklogDML',
            'SOBCURR'               : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SORMCRL'               : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SORCMNR'               : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SORCCON'               : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SORCMJR'               : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SARWAPC'               : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SARWADF'               : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SFRSTCR'               : 'net.hedtech.banner.seeddata.SfrstcrDML',
            'GOBTPAC'               : 'net.hedtech.banner.seeddata.GobtpacDML',
            'SSUSER_SPRIDEN'        : 'net.hedtech.banner.seeddata.SSUserPersonIDDML',
            'GOBTPAC_RECORD'        : 'net.hedtech.banner.seeddata.ThirdPartyAccessPinDML',
            'GENIDEN'               : 'net.hedtech.banner.seeddata.ProxyAccessCredentialInformationDML',
            'GERATTD'               : 'net.hedtech.banner.seeddata.EventRegistrantDML',
            'GERFGST'               : 'net.hedtech.banner.seeddata.EventGuestDML',
            'GOBQSTN'               : 'net.hedtech.banner.seeddata.PinQuestionDML',
            'GOBANSR'               : 'net.hedtech.banner.seeddata.PersonPinResponseDML',
            'EVENT_SSB_AVAILABLE'   : 'net.hedtech.banner.seeddata.EventSSBAvailabilityDML',
            'SHRINCG'               : 'net.hedtech.banner.seeddata.IncompleteGradesDML',
            'SSBSECT_DELETE'        : 'net.hedtech.banner.seeddata.ScheduleTermDeleteDML',
            'CATALOG_DELETE'        : 'net.hedtech.banner.seeddata.CatalogDeleteDML',
            'SORATMT'               : 'net.hedtech.banner.seeddata.SoratmtDML',
            'SFRBRDB'               : 'net.hedtech.banner.seeddata.RegistrationGroupRuleDetailDML',
            'SFRBRDH'               : 'net.hedtech.banner.seeddata.RegistrationGroupRuleDML',
            'SORSATR'               : 'net.hedtech.banner.seeddata.SorsatrDML',
            'SFRBSEL'               : 'net.hedtech.banner.seeddata.RegistrationSelectedBlockDML',
            'SFRBLPA'               : 'net.hedtech.banner.seeddata.RegistrationBlockPreAssignmentDML',
            'RECRUIT_SPRIDEN'       : 'net.hedtech.banner.seeddata.RecruitPersonDML',
            'SHRGCOM'               : 'net.hedtech.banner.seeddata.ShagcomDML',
            'SHRSCOM'               : 'net.hedtech.banner.seeddata.ShagcomDML',
            'SHRMRKS'               : 'net.hedtech.banner.seeddata.ShagcomDML',
            'SHRSMRK'               : 'net.hedtech.banner.seeddata.ShagcomDML',
            'SGRADVR'               : 'net.hedtech.banner.seeddata.SgradvrDML',
            'SORNOTE'               : 'net.hedtech.banner.seeddata.SornoteDML',
            'SORATRK'               : 'net.hedtech.banner.seeddata.SoratrkDML',
            'FLEXREGFEE'            : 'net.hedtech.banner.seeddata.FlexRegFeeDML',
            'SMBPGEN'               : 'net.hedtech.banner.seeddata.CappProgramRequirementDML',
            'STVGCHG'               : 'net.hedtech.banner.seeddata.GradeChangeReasonDML',
            'GCRFLDR'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRCFLD'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRPARM'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRFLPM'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBQURY'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBTMPL'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBEMTL'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBMNTL'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBLTPL'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRITPE'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBEVMP'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRTPFL'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRMBAC'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBSPRP'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRORAN'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GLBEXTR'               : 'net.hedtech.banner.seeddata.GlbextrDML',
            'GCBACTM'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCVASTS'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRAACT'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRACNT'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCBAGRP'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCBPBTR'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRAISR'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRABLK'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRAGRA'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCBPOPL'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRPOPV'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            //'GCBQURY'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRQRYV'               : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRPOPC'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'MARKACTIONITEMPOSTED'  : 'net.hedtech.banner.seeddata.MarkActionItemPostedDML',
            'MARKACTIONITEMGROUPPOSTED'  : 'net.hedtech.banner.seeddata.MarkActionItemGroupPostedDML',
            'GCRPQID'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRPVID'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRLENT'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRSLIS'               : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GURNDSP'               : 'net.hedtech.banner.seeddata.AdvisingNameDisplayDML',
            'FINANCEFISCAYEAR'      : 'net.hedtech.banner.seeddata.FinanceProcurementFiscalYearDML',
            'FINANCEUSER'           : 'net.hedtech.banner.seeddata.FinanceProcurementUserDML',
            'UPDATEFOBPROF'         : 'net.hedtech.banner.seeddata.FinanceProcurementUserProfileUpdateDML',
            'UPDATEFOBSYSC'         : 'net.hedtech.banner.seeddata.FinanceSystemControlDML',
            'FPBREQH'               : 'net.hedtech.banner.seeddata.FinanceProcurementHeaderCreateDML',
            'FOAPAL_ORGANIZATIONS'  : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityFoapalOrganizationDML',
            'FOAPAL_ACCUNT'         : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityFoapalAccountDML',
            'FOAPAL_PROGRAMS'       : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityFoapalProgramDML',
            'FOAPAL_LOCATION'       : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityFoapalLocationDML',
            'FOAPAL_ACTIVITY'       : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityFoapalActivityDML',
            'BA_VENDORS'            : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityVendorDML',
            'BA_JOUNRAL_VOUCHER'    : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityCreateBudgetJournalVoucherDML',
            'CLEAN_NHRDIS'          : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityCleanPayrollEntriesDML',
            'UPDATE_PIDM_NHRDIST'   : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityUpdatePayrollEntriesDML',
            'PURCHASE_REQUISITION'  : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityCreatePurchaseRequisitionsDML',
            'BA_FGBTRNH'            : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityTransactionHistoryDML',
            'BA_FGBTRND'            : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityTransactionDetailsDML',
            'PURCHASE_ORDER'        : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityCreatePurchaseOrderDML',
            'BA_QUERY_PROTOTYPE'    : 'net.hedtech.banner.seeddata.FinanceBudgetQueryProtoTypesDML',
            'BA_FAV_QUERY_PROTOTYPE': 'net.hedtech.banner.seeddata.FinanceFavoriteBudgetQueryProtoTypesDML',
            'BA_VIEW_PENDING_DOCS'  : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityViewPendingDocumentsHistoryDML',
            'BA_FORCOMP'            : 'net.hedtech.banner.seeddata.FinanceBudgetComputedColumnsDML',
            'FTVDISC'               : 'net.hedtech.banner.seeddata.FinanceDiscountCreateDML',
            'FTVTGRP'               : 'net.hedtech.banner.seeddata.FinanceTaxGroupCreateDML',
            'FTVTRAT'               : 'net.hedtech.banner.seeddata.FinanceTaxRateCreateDML',
            'FTRTGTR'               : 'net.hedtech.banner.seeddata.FinanceTaxGroupAndRateCreateDML',
            'TBBCSTU'               : 'net.hedtech.banner.seeddata.TbbcstuDML',
            'PEBEMPL'               : 'net.hedtech.banner.seeddata.EmployeePersonIDDML',
            'PEBEMPLEAVEBYJOB'      : 'net.hedtech.banner.seeddata.EmployeeLeaveByJobPersonIDDML',
            'PDRBDED'               : 'net.hedtech.banner.seeddata.EmployeeBenefitsIDDML',
            'PDRDEDN'               : 'net.hedtech.banner.seeddata.EmployeeBenefitsDetailDML',
            'PERDHIS'               : 'net.hedtech.banner.seeddata.PerdhisDML',
            'PERJHIS'               : 'net.hedtech.banner.seeddata.PerjhisDML',
            'NBBPOSN'               : 'net.hedtech.banner.seeddata.NbbposnDML',
            'NBRPTOT'               : 'net.hedtech.banner.seeddata.NbrptotDML',
            'NBRBJOB'               : 'net.hedtech.banner.seeddata.EmployeeJobAssignmentDML',
            'NBRJOBS'               : 'net.hedtech.banner.seeddata.EmployeeJobAssignmentDetailDML',
            'NBREARN'               : 'net.hedtech.banner.seeddata.EmployeeJobEarningsDML',
            'BANNERUSER'            : 'net.hedtech.banner.seeddata.BannerUserDML',
            'HRGOBEACCUSER'         : 'net.hedtech.banner.seeddata.HrGobeaccDML',
            'ORACLEUSER'            : 'net.hedtech.banner.seeddata.CreateOracleUserDML',
            'PAGEBUILDERUSER'       : 'net.hedtech.banner.seeddata.CreatePageBuilderUserDML',
            'GENERALAUTOUSER'       : 'net.hedtech.banner.seeddata.CreateGeneralAutoUserDML',
            'GENERALAUTONEWPAGES'   : 'net.hedtech.banner.seeddata.GeneralAutoNewPagesDML',
            'AIPORACLEUSER'         : 'net.hedtech.banner.seeddata.GeneralAIPOracleUserDML',
            'WEBTAILORUSER'         : 'net.hedtech.banner.seeddata.CreateWebtailorUserDML',
            'NTRLRAQ'               : 'net.hedtech.banner.seeddata.NtrlraqDML',
            'FINANCECIFOAPALCLEAN'  : 'net.hedtech.banner.seeddata.FinanceCifoapalpCleanUpDML',
            'PHRELBD'               : 'net.hedtech.banner.seeddata.PhrelbdDML',
            'PTRECPD'               : 'net.hedtech.banner.seeddata.PtrecpdDML',
            'PHRECRT'               : 'net.hedtech.banner.seeddata.PhrecrtDML',
            'PHRECST'               : 'net.hedtech.banner.seeddata.PhrecstDML',
            'PHRECSN'               : 'net.hedtech.banner.seeddata.PhrecsnDML',
            'PHRECSC'               : 'net.hedtech.banner.seeddata.PhrecscDML',
            'PHRECSI'               : 'net.hedtech.banner.seeddata.PhrecsiDML',
            'PHRECRQ'               : 'net.hedtech.banner.seeddata.PhrecrqDML',
            'PHRECRS'               : 'net.hedtech.banner.seeddata.PhrecrsDML',
            'PHRECDT'               : 'net.hedtech.banner.seeddata.PhrecdtDML',
            'PTRECER'               : 'net.hedtech.banner.seeddata.PtrecerDML',
            'PTRECPC'               : 'net.hedtech.banner.seeddata.PtrecpcDML',
            'PHRECAL'               : 'net.hedtech.banner.seeddata.PhrecalDML',
            'PHRECFD'               : 'net.hedtech.banner.seeddata.PhrecfdDML',
            'PTRECEC'               : 'net.hedtech.banner.seeddata.PtrececDML',
            'PTRECPR'               : 'net.hedtech.banner.seeddata.PtrecprDML',
            'GUBAPPL'               : 'net.hedtech.banner.seeddata.GubapplDML',
            'GUROCFG'               : 'net.hedtech.banner.seeddata.GurocfgDML',
            'GURCTLEP'              : 'net.hedtech.banner.seeddata.GurctleppDML',
            'GURAPPR'               : 'net.hedtech.banner.seeddata.GurapprDML',
            'PERJOBS_EXTRACT'       : 'net.hedtech.banner.seeddata.EmployeeTimeEntryExtractDML',
            'PEREARN'               : 'net.hedtech.banner.seeddata.PerearnDML',
            'PERHOUR'               : 'net.hedtech.banner.seeddata.PerhourDML',
            'PERTITO'               : 'net.hedtech.banner.seeddata.PertitoDML',
            'PERELBD'               : 'net.hedtech.banner.seeddata.PerelbdDML',
            'PERLVTK'               : 'net.hedtech.banner.seeddata.PerlvtkDML',
            'PERJOBS_MESSAGE'       : 'net.hedtech.banner.seeddata.EmployeeTimeEntryMessageDML',
            'NBRRJQE'               : 'net.hedtech.banner.seeddata.NbrrjqeDML',
            'NTRINST'               : 'net.hedtech.banner.seeddata.NtrinstDML',
            'NTRECDQ'               : 'net.hedtech.banner.seeddata.NtrecdqDML',
            'NTRQPRT'               : 'net.hedtech.banner.seeddata.NtrqprtDML',
            'PERFORMANCE_SQL'       : 'net.hedtech.banner.seeddata.PlsqlDML',
            'PCRBENE'               : 'net.hedtech.banner.seeddata.EmployeeCobraBeneficiariesDML',
            'GJRJLIS'               : 'net.hedtech.banner.seeddata.JobsubSavedOutputDml',
            'SHBCGPA'               : 'net.hedtech.banner.seeddata.ShbcgpaDML',
            'FGBJVCH'               : 'net.hedtech.banner.seeddata.FinanceJournalHeaderCreateDML',
            'FGBJVCD'               : 'net.hedtech.banner.seeddata.FinanceJournalDetailCreateDML',
            'NTRQGRP'               : 'net.hedtech.banner.seeddata.NtrqgrpDML',
            'PTRCALN_LEAVEREQ'      : 'net.hedtech.banner.seeddata.PtrcalnLeaveReqDML',
			'FPBPOHD'               : 'net.hedtech.banner.seeddata.FinancePurchaseOrderHeaderCreateDML',
            'FABINVH'               : 'net.hedtech.banner.seeddata.FinanceBudgetAvailabilityInvoiceCreateDML'
    ]

    // map of tables that require both an api class but also will update / insert via the dynamic sql table process
    def both = [
            'SOBCURR' : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SORMCRL' : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SORCMNR' : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SORCCON' : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SORCMJR' : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SARWAPC' : 'net.hedtech.banner.seeddata.SoacurrDML',
            'SARWADF' : 'net.hedtech.banner.seeddata.SoacurrDML',
            'GOBTPAC' : 'net.hedtech.banner.seeddata.GobtpacDML',
            'SFRSTCR' : 'net.hedtech.banner.seeddata.SfrstcrDML',
            'SORATMT' : 'net.hedtech.banner.seeddata.SoratmtDML',
            'SORSATR' : 'net.hedtech.banner.seeddata.SorsatrDML',
            'SHRGCOM' : 'net.hedtech.banner.seeddata.ShagcomDML',
            'SHRSCOM' : 'net.hedtech.banner.seeddata.ShagcomDML',
            'SHRMRKS' : 'net.hedtech.banner.seeddata.ShagcomDML',
            'SHRSMRK' : 'net.hedtech.banner.seeddata.ShagcomDML',
            'SGRADVR' : 'net.hedtech.banner.seeddata.SgradvrDML',
            'SORNOTE' : 'net.hedtech.banner.seeddata.SornoteDML',
            'SORATRK' : 'net.hedtech.banner.seeddata.SoratrkDML',
            'SMBPGEN' : 'net.hedtech.banner.seeddata.CappProgramRequirementDML',
            'GCRFLDR' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRCFLD' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRPARM' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRFLPM' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBQURY' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBTMPL' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBEMTL' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBMNTL' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBLTPL' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRITPE' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBEVMP' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRTPFL' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRMBAC' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCBSPRP' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRORAN' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GLBEXTR' : 'net.hedtech.banner.seeddata.GlbextrDML',
            'GCBACTM' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCVASTS' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRAACT' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRACNT' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCBAGRP' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCBPBTR' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRAISR' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRABLK' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRAGRA' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCBPOPL' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRPOPV' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            //'GCBQURY': 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRQRYV' : 'net.hedtech.banner.seeddata.GcrfldrDML',
            'GCRPOPC' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRPQID' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRPVID' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRLENT' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GCRSLIS' : 'net.hedtech.banner.seeddata.GeneralActionItemDML',
            'GURNDSP' : 'net.hedtech.banner.seeddata.AdvisingNameDisplayDML',
            'TBBCSTU' : 'net.hedtech.banner.seeddata.TbbcstuDML',
            'PERDHIS' : 'net.hedtech.banner.seeddata.PerdhisDML',
            'NBBPOSN' : 'net.hedtech.banner.seeddata.NbbposnDML',
            'NBRPTOT' : 'net.hedtech.banner.seeddata.NbrptotDML',
            'PERJHIS' : 'net.hedtech.banner.seeddata.PerjhisDML',
            'NTRLRAQ' : 'net.hedtech.banner.seeddata.NtrlraqDML',
            'PHRELBD' : 'net.hedtech.banner.seeddata.PhrelbdDML',
            'PTRECPD' : 'net.hedtech.banner.seeddata.PtrecpdDML',
            'PHRECRT' : 'net.hedtech.banner.seeddata.PhrecrtDML',
            'PHRECST' : 'net.hedtech.banner.seeddata.PhrecstDML',
            'PHRECSN' : 'net.hedtech.banner.seeddata.PhrecsnDML',
            'PHRECSC' : 'net.hedtech.banner.seeddata.PhrecscDML',
            'PHRECSI' : 'net.hedtech.banner.seeddata.PhrecsiDML',
            'PHRECRQ' : 'net.hedtech.banner.seeddata.PhrecrqDML',
            'PHRECRS' : 'net.hedtech.banner.seeddata.PhrecrsDML',
            'PHRECDT' : 'net.hedtech.banner.seeddata.PhrecdtDML',
            'PTRECER' : 'net.hedtech.banner.seeddata.PtrecerDML',
            'PTRECPC' : 'net.hedtech.banner.seeddata.PtrecpcDML',
            'PTRECPR' : 'net.hedtech.banner.seeddata.PtrecprDML',
            'PHRECAL' : 'net.hedtech.banner.seeddata.PhrecalDML',
            'PHRECFD' : 'net.hedtech.banner.seeddata.PhrecfdDML',
            'PTRECEC' : 'net.hedtech.banner.seeddata.PtrececDML',
            'GUBAPPL' : 'net.hedtech.banner.seeddata.GubapplDML',
            'GUROCFG' : 'net.hedtech.banner.seeddata.GurocfgDML',
            'GURCTLEP': 'net.hedtech.banner.seeddata.GurctleppDML',
            'GURAPPR' : 'net.hedtech.banner.seeddata.GurapprDML',
            'PEREARN' : 'net.hedtech.banner.seeddata.PerearnDML',
            'PERHOUR' : 'net.hedtech.banner.seeddata.PerhourDML',
            'PERTITO' : 'net.hedtech.banner.seeddata.PertitoDML',
            'PERELBD' : 'net.hedtech.banner.seeddata.PerelbdDML',
            'PERLVTK' : 'net.hedtech.banner.seeddata.PerlvtkDML',
            'NBRRJQE' : 'net.hedtech.banner.seeddata.NbrrjqeDML',
            'NTRINST' : 'net.hedtech.banner.seeddata.NtrinstDML',
            'NTRECDQ' : 'net.hedtech.banner.seeddata.NtrecdqDML',
            'NTRQPRT' : 'net.hedtech.banner.seeddata.NtrqprtDML',
            'PCRBENE' : 'net.hedtech.banner.seeddata.EmployeeCobraBeneficiariesDML',
            'GJRJLIS' : 'net.hedtech.banner.seeddata.JobsubSavedOutputDml',
            'SHBCGPA' : 'net.hedtech.banner.seeddata.ShbcgpaDML',
            'NTRQGRP' : 'net.hedtech.banner.seeddata.NtrqgrpDML'
    ]


    def findClass( tableName ) {
        def apiMap = API.find {it.key == tableName}
        return apiMap?.value
    }


    def isBoth( tableName ) {
        def apiMap = both.find {it.key == tableName}
        return apiMap?.value
    }


}
